export const REQUEST_CHIRPS = "REQUEST_CHIRPS";
export const FETCH_CHIRPS_SUCCESS = "FETCH_CHIRPS_SUCCESS";
export const FETCH_CHIRPS_FAILURE = "FETCH_CHIRPS_FAILURE";
export const REQUEST_CREATE_CHIRP = "REQUEST_CREATE_CHIRP";
export const CREATE_CHIRP_SUCCESS = "CREATE_CHIRP_SUCCESS";
export const CREATE_CHIRP_FAILURE = "CREATE_CHIRP_FAILURE";